In [2]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0])

[1 2 3 4]


In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.empty(4)

array([2.12199579e-314, 1.93101617e-312, 2.21341409e-321, 1.07372987e-311])

In [7]:
print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [8]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [9]:
arr=np.array([1,2,3,4,5,6,7,8])
np.append([1,2],arr)

array([1, 2, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [21]:
arr=np.array([2,3,5,7,1,4,6])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
array_example=np.array([[[0,1,2,3],
                         [4,5,6,7]],
                        
                        [[0,1,2,3],
                        [4,5,6,7]],
                        
                        [[0,1,2,3],
                        [4,5,6,7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [27]:
array_example.ndim

3

In [25]:
array_example.size

24

In [32]:
arr_one=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr_one)
arr_one.ndim


[[1 2 3 4 5]
 [2 3 4 5 6]]


2

In [33]:
arr_one.size

10

In [34]:
arr_one.shape

(2, 5)

In [3]:
import numpy as np
tes=np.array([1,2,3,4])
tes.ndim

1

In [4]:
np.arange(1,8,3)

array([1, 4, 7])

In [6]:
a=np.array([1,2,3,4])
b=np.append(a,[5,6])
print(b)

[1 2 3 4 5 6]


In [11]:
a=np.array([[3,4,5],[1,2,3]])
b=np.delete(a,1,0)
print(b)
            

[[3 4 5]]


In [12]:
#np.reshape()
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [14]:
b=a.reshape(3,2)
c=a.reshape(6,1)
print(b)
print(c)

[[0 1]
 [2 3]
 [4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [17]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [20]:
b=a[np.newaxis]
print(b.shape)
print(b.ndim)
print(b)

(1, 6)
2
[[1 2 3 4 5 6]]


In [22]:
b=np.expand_dims(a,axis=1)
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [23]:
c=np.expand_dims(a,axis=0)
c.shape

(1, 6)

In [29]:
#indexing
data=np.array([1,2,3])
print(data)
print(data[0])
print(data[0:2])
print(data[1:])
print(data[::-1])

[1 2 3]
1
[1 2]
[2 3]
[3 2 1]


In [30]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [32]:
four_up=(a>=4)
print(a[four_up])

[ 4  5  6  7  8  9 10 11 12]


In [33]:
habis_dibagi2=a[a%2==0]
print(habis_dibagi2)

[ 2  4  6  8 10 12]


In [34]:
c=a[(a>3)&(a%2==0)]
print(c)

[ 4  6  8 10 12]


In [36]:
#slicing
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [19]:
#menumpuk array secara vertikal dengan vstack
import numpy as np
a_1=np.array([[1,1],
              [2,2]])
a_2=np.array([[3,3],
              [4,4]])
np.vstack((a_2,a_1))

array([[3, 3],
       [4, 4],
       [1, 1],
       [2, 2]])

In [8]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [3]:
#membagi array menjadi bbrp array yang lebih kecil dengan hsplit
arrsplit=np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                  [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

NameError: name 'np' is not defined

In [42]:
#membagi array menjadi tiga array 
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [43]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
#membuat array yang sama dari array sebelumnya

b=a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
#mengcopy data
c=a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# operasi hitung pada array

In [46]:
a=np.array([1,2,3,4])
a.sum()

10

In [47]:
b=np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [49]:
print(b.sum(axis=0))
print(b.sum(axis=1))

[3 3]
[2 4]


In [50]:
data=np.array([1,2])
data

array([1, 2])

In [52]:
ones=np.ones(2)
ones

array([1., 1.])

In [53]:
data+ones

array([2., 3.])

In [54]:
data*data

array([1, 4])

In [55]:
data/data

array([1., 1.])

# BROADCASTING

In [56]:
data*1.6

array([1.6, 3.2])

In [60]:
print(data.max())
print(data.min())
print(data.sum())
print(data.prod())#perkalian antar elemen
print(data.std())#standar deviasi)


2
1
3
2
0.5


In [61]:
A=np.array([[0.45053, 0.17234,0.341253,0.5510652],
           [0.562134, 0.0509312, 0.40002134,0.112345],
           [0.21456,0.112321,0.023452,0.122432]])
print(A)

[[0.45053    0.17234    0.341253   0.5510652 ]
 [0.562134   0.0509312  0.40002134 0.112345  ]
 [0.21456    0.112321   0.023452   0.122432  ]]


In [62]:
A.sum()

3.11338474

In [63]:
A.min()

0.023452

In [64]:
A.min(axis=0)

array([0.21456  , 0.0509312, 0.023452 , 0.112345 ])

In [65]:
A.max()

0.562134

In [67]:
A.max(axis=1)

array([0.5510652, 0.562134 , 0.21456  ])

In [68]:
A.std()

0.1849458915677479

# creating matrices

In [73]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [74]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [76]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [77]:
np.random.random((3,2))

array([[0.84800891, 0.51161639],
       [0.03246974, 0.35806802],
       [0.35816243, 0.37464783]])

# Matrix Arithmetic

In [83]:
data=np.array([[1,2],[3,4]])
ones=np.ones((2,2))
jumlah=data+ones
print(data)
print(ones)
print(jumlah)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[2. 3.]
 [4. 5.]]


In [86]:
ones_row=np.ones([1,2])
print(ones_row)
print(data+ones_row)

[[1. 1.]]
[[2. 3.]
 [4. 5.]]


In [88]:
#dot product
a_1=np.array([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)
a_2=np.array([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [89]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

In [90]:
#matrix indexing
data=np.array([[1,2],[3,4],[5,6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [91]:
data[0,1]

2

In [92]:
data[0:2,1]

array([2, 4])

In [93]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [98]:
#matrix aggregation
print(data)
print(data.max())
print(data.min())
print(data.sum())

[[1 2]
 [3 4]
 [5 6]]
6
1
21


In [100]:
print(data.max(axis=0))
print(data.min(axis=1))

[5 6]
[1 3 5]


In [102]:
##Transposing and Reshaping
print(data)
print(data.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [103]:
data_col=np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [104]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
arr=np.arange(6).reshape((2,3))
print(arr)
arr.transpose

[[0 1 2]
 [3 4 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

In [112]:
ndarr=np.array([[[1,2],[3,4]],
               [[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [113]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [114]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [115]:
print(np.random.random((4,3,2)))

[[[0.65807191 0.79379979]
  [0.15564738 0.98778747]
  [0.34106358 0.1925547 ]]

 [[0.06803984 0.33956729]
  [0.19169951 0.46898242]
  [0.18808777 0.51141794]]

 [[0.63856487 0.60714233]
  [0.33796424 0.52645844]
  [0.41709309 0.700536  ]]

 [[0.95112839 0.93924129]
  [0.49511165 0.48113677]
  [0.30304286 0.22876293]]]


In [21]:
#Meratakan N-dimensional array
import numpy as np
arrflat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
import numpy as np
myArray=np.array((1,2,3,4))
print(myArray)
print(myArray*5)
print(myArray/5)
print(myArray//2)
print(myArray%2)
print(myArray**2)
print(myArray!=2)
print(myArray==3)
print(myArray>=1)

[1 2 3 4]
[ 5 10 15 20]
[0.2 0.4 0.6 0.8]
[0 1 1 2]
[1 0 1 0]
[ 1  4  9 16]
[ True False  True  True]
[False False  True False]
[ True  True  True  True]


In [45]:
import numpy as np
a=np.array(([1,2],
   [2,3,]))
b=np.array(([2,2],
   [4,5]))
print(a)
print(b)
print(a+b)
print(a[a>2], b[b>2])


[[1 2]
 [2 3]]
[[2 2]
 [4 5]]
[[3 4]
 [6 8]]
[3] [4 5]


In [58]:
a=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])

print(a[0:,1:3])

[[ 2  3]
 [ 5  6]
 [ 9 10]]


In [63]:
#import data dari file csv
myData=np.genfromtxt("./data.csv", skip_header=1, delimiter=",", filling_values=60)

In [64]:
print(myData)

[[ 75.  60.  80. 100.]
 [ 30.  40.  50.  60.]
 [ 80.  90.  99.  85.]
 [ 60.  71.  65.  55.]]


In [67]:
rata2=np.mean(myData, axis=1)
print(np.amax(myData, axis=0))
print(rata2)

[ 80.  90.  99. 100.]
[78.75 45.   88.5  62.75]


In [74]:
myData2=np.append(myData, [[85,90,77,56]], axis=0)
myData2

array([[ 75.,  60.,  80., 100.],
       [ 30.,  40.,  50.,  60.],
       [ 80.,  90.,  99.,  85.],
       [ 60.,  71.,  65.,  55.],
       [ 85.,  90.,  77.,  56.]])

In [77]:
myStudentData=np.append(myData, [[85,90,77,56]], axis=0)
myStudentData

array([[ 75.,  60.,  80., 100.],
       [ 30.,  40.,  50.,  60.],
       [ 80.,  90.,  99.,  85.],
       [ 60.,  71.,  65.,  55.],
       [ 85.,  90.,  77.,  56.]])

In [89]:
myStudentData=np.genfromtxt("./data.csv", skip_header=1, delimiter=",", filling_values=60)
np.lookfor("median")

Search results for 'median'
---------------------------
numpy.median
    Compute the median along the specified axis.
numpy.nanmedian
    Compute the median along the specified axis, while ignoring NaNs.
numpy.ma.median
    Compute the median along the specified axis.
numpy.pad
    Pad an array.
numpy.quantile
    Compute the q-th quantile of the data along the specified axis.
numpy.percentile
    Compute the q-th percentile of the data along the specified axis.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.nanpercentile
    Compute the qth percentile of the data along the specified axis,
numpy.random.Generator.logistic
    Draw samples from a logistic distribution.
numpy.random.RandomState.logistic
    Draw samples from a logistic distribution.
numpy.ma.tests.test_extras.TestMedian.test_docstring_examples
    test the examples given in the docstring of ma.median

In [90]:
print(np.var(myStudentData,axis=0))
print(np.std(myStudentData,axis=0))
print(np.median(myStudentData))

[ 31.25    59.5    204.6875 489.1875]
[ 5.59016994  7.71362431 14.30690393 22.1175835 ]
72.5


In [92]:
[x,y]= myStudentData.shape
myStudentData[2:y,3:x]

array([[90.],
       [75.]])

In [95]:
myNewStudent=np.delete(myStudentData,3,axis=0 )
myNewStudent

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.]])

In [99]:
#reshape and resize
newReshape=myNewStudent.reshape(2,6)
print(newReshape)

[[70. 75. 80. 30. 75. 80.]
 [90. 68. 65. 77. 60. 90.]]


In [102]:
#np.eye
eyes=np.eye(3,3)
print(eyes)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [106]:
array_1=np.array([[1,3,5],
                 [4,4,4]])
array_2=np.array([[1,1,5],
                 [4,3,4]])
array_3=np.array([[3,3],
                 [4,3]])

In [107]:
jumlah=np.transpose(array_1)+np.transpose(array_2)

array([[ 2,  8],
       [ 4,  7],
       [10,  8]])

In [112]:
oneDarray=np.array([1,2,3,4,5,6,7,8])
twoDarray=oneDarray.reshape(2,4)

In [114]:
[y,x]=twoDarray.shape
backToOneD=twoDarray.reshape(1,x*y)[0]
backToOneD

array([1, 2, 3, 4, 5, 6, 7, 8])